<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTyvuzq4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTyvuzq4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTyvuzq4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTyvuzq4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTyvuzq4\appProdProjectContainer([
    'container.build_hash' => 'Tyvuzq4',
    'container.build_id' => '9980bd79',
    'container.build_time' => 1578855778,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTyvuzq4');
